DjangoWeb/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('post/', include('blogapps.urls')),
    path('', include('userapps.urls')),
    path('api/', include('api.urls')),
]

api/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views. api_routes),
    path('posts/', views.get_posts),
    path('posts/<str:pk>/', views.get_post),
]

blogapps/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('show/', views.index, name='blog'),
    path('view/<str:post_id>', views.show_post, name='showpost'),
    path('create', views.create_post, name='createpost'),
    path('edit/<str:post_id>', views.edit_post, name='editpost'),
]

userapps/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.user_register, name='register'),
    path('', views.user_home, name='home'),
]

blogapps/models.py
from django.db import models
import uuid
from django.contrib.auth.models import User
# Create your models here.

class UserPost (models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, unique=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    title = models.CharField(max_length=100)
    desc = models.TextField(null=True, blank=True) # null/blank = True will set form input to not required
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)

    #return username title desc id
    def __str__(self):
        return self.user.username

userapps/models.py
from django.db import models

# Create your models here.

blogapps/forms.py
from django.forms import ModelForm
from .models import UserPost
from django import forms

class UserPostForm(ModelForm):
    class Meta:
        model = UserPost
        fields = '__all__'
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'desc': forms.Textarea(attrs={'class': 'form-control'}),
            'username': forms.TextInput(attrs={'class': 'form-control'}),
        }
        

api/views.py
from django.http import JsonResponse
from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework import status
from .serializers import PostSerializer
from .serializers import ManagePostSerializer
from blogapps.models import UserPost

@api_view(['GET'])
def api_routes(request):
    
    routes = [
        { 'GET': '/api/posts'},
        { 'GET': '/api/posts/id'},
    ]

    return Response(routes)

@api_view(['GET', 'POST'])
def get_posts(request):
    if request.method == 'GET':
        posts = UserPost.objects.all()
        serializer = PostSerializer(posts, many=True)
        return Response({'all_post':serializer.data}, status=status.HTTP_200_OK)
    
    if request.method == 'POST':
        serializer = ManagePostSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response({'status':status.HTTP_201_CREATED, "created" : serializer.data}, status=status.HTTP_201_CREATED)
        else:
            return Response({'status':status.HTTP_400_BAD_REQUEST, "created" : serializer.errors}, status=status.HTTP_400_BAD_REQUEST)
    

@api_view(['GET', 'PUT', 'DELETE'])
def get_post(request, pk):
    try:
       post = UserPost.objects.get(id=pk)
    except UserPost.DoesNotExist:
        return Response({'status':status.HTTP_404_NOT_FOUND}, status=status.HTTP_404_NOT_FOUND)
    
    if request.method == 'GET':
        serializer = PostSerializer(post, many=False)
        if(status.HTTP_200_OK == 200):
            return Response({'selected_post':serializer.data}, status=status.HTTP_200_OK)
        else:
            return Response({'status':status.HTTP_404_NOT_FOUND},status=status.HTTP_404_NOT_FOUND)
    elif request.method == 'PUT':
        serializer = ManagePostSerializer(post, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response({'status':status.HTTP_200_OK, "updated" : serializer.data}, status=status.HTTP_200_OK)
        else:
            return Response({'status':status.HTTP_400_BAD_REQUEST, "updated" : serializer.errors}, status=status.HTTP_400_BAD_REQUEST)
    elif request.method == 'DELETE':
        post.delete()
        return Response({'status':status.HTTP_204_NO_CONTENT, "deleted" : "deleted"}, status=status.HTTP_204_NO_CONTENT)
    

blogapps/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from blogapps.models import UserPost
from .forms import UserPostForm
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    post_data = UserPost.objects.all()
    return render(request, 'index.html' , {'post_data': post_data})

def show_post(request, post_id):
    post_data = UserPost.objects.get(id=post_id)
    if request.method == 'POST':
        if request.user.is_authenticated:
            post_data.delete()
            return redirect('blog')
        else:
            return redirect('login')
    else:
        context = {'post_data': post_data}
        return render(request, 'post.html', context)
    

@login_required(login_url='login')
def create_post(request):
    post_form = UserPostForm()
    if request.method == 'POST':
        post_form = UserPostForm(request.POST)
        if post_form.is_valid():
            post_form.save()
            return redirect('blog')
        else:
            return HttpResponse("Error Create Post")

    dict_form = {'post_form': post_form}
    return render(request, 'add_post.html', dict_form)

@login_required(login_url='login')
def edit_post(request, post_id):
    post_data = UserPost.objects.get(id=post_id)
    post_form = UserPostForm(instance=post_data)
    if request.method == 'POST':
        post_form = UserPostForm(request.POST, instance=post_data)
        if post_form.is_valid():
            post_form.save()
            return redirect('blog')
        else:
            return HttpResponse("Error Update Post")

    dict_form = {'post_form': post_form}
    return render(request, 'add_post.html', dict_form)

userapps/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages

def user_login(request):
    if request.user.is_authenticated:
        return redirect('home')

    if(request.method == 'POST'):
        username = request.POST['username']
        password = request.POST['password']
        print(username, password)

        try:
            user = User.objects.get(username=username)
        except:
            user = None
            print('User not found')
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('home')
        else:
            messages.error(request, "Username or Password is incorrect.")

    return render(request, 'login_user.html')

def user_register(request):
    page = 'register'
    form = UserCreationForm()

    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.username = user.username.lower()
            user.save()
            login(request, user)
            return redirect('home')
        else:
            messages.error(request, "An error occurred during registration.")
    register_dict = {'page': page, 'form': form}
    return render(request, 'login_user.html', register_dict)


def user_logout(request):
    logout(request)
    return redirect('login')

@login_required(login_url='login')
def user_home(request):
    return render(request, 'home_user.html')

blogapps/templates/add_post.html
{% extends 'main.html' %}

{% block title %}Create Post{% endblock title %}


{% block content %}
<div class="mx-5 mt-3 bg-success">
    <p class="text-center pt-4 fw-light fs-2">Form</p>
    <div class="row p-3">
        <form action="" method="POST" class="p-4 col-lg-5 col-sm-12">
            {% csrf_token %}
            {% comment %} //generate form in one line {{post_form.as_div}} {% endcomment %}
            <input type="hidden" name="user" id="id_user" value="{% if user.is_authenticated %}{{user.id}}{% endif %}">
            <div class="input-group mb-3">
                <span class="input-group-text" id="basic-addon1">{{post_form.title.label}}</span>
                {{post_form.title}}
            </div>
            <div class="input-group mb-3">
                <span class="input-group-text" id="basic-addon1">Description</span>
                {{post_form.desc}}
            </div>
            
            <input type="submit" class="btn btn-light" value="Submit">
            <a href="{% url 'blog' %}" class="btn btn-light mx-2">Cancel</a>
        </form>
        <div class="col-lg-7 col-sm-12 p-5">
            <img src="https://indigo.amsterdam/wp-content/uploads/2017/05/python-django-logo-1024x576.jpg" alt="django"
                width="100%" height="100%">
        </div>

    </div>

</div>

{% endblock content %}

blogapps/templates/index.html
{% extends 'main.html' %}

{% block title %}Django Blog{% endblock title %}

{% block navbar %}
<a href="/post/create" class="btn btn-outline-light">✏️</a>
{% endblock navbar %}



{% block content %}
{% for post in post_data %}
<div class="card mx-4 my-2">
    <div class="card-header">
        @{{post.user.username}}
    </div>
    <div class="card-body">
        <h5 class="card-title">{{post.title}}</h5>
        <a href="/post/view/{{post.id}}" class="btn btn-dark">See More</a>
    </div>
</div>
{% endfor %}
{% endblock content %}

blogapps/templates/post.html
{% extends 'main.html' %}

{% block title %}Post{% endblock title %}

{% block navbar %}
<a href="{% url 'createpost' %}" class="btn btn-outline-light">✏️</a>
{% endblock navbar %}



{% block content %}
<div class="card mx-5 mt-3">
  <div class="card-header">
    <div class="row">
      <p class="col">{{post_data.title}}</p>
      {% if user.username ==  post_data.user.username %}
      <div class="col d-flex justify-content-end">
        <a href="{% url 'editpost' post_data.id %}" class="btn btn-outline-secondary mx-2">Update</a>
        <form action="" method="POST">
          {% csrf_token %}
          <button type="submit" class="btn btn-outline-danger mx-2">Delete</button>
        </form>
        
      </div>
      {% endif %}
    </div>
  </div>
  <div class="card-body">
    <blockquote class="blockquote mb-0">
      <p>{{post_data.desc}}</p>
      <footer class="blockquote-footer">@{{post_data.user.username}}</footer>
    </blockquote>
  </div>
</div>
{% endblock content %}

templates/main.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <title>{% block title %}

        {% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'styles/style.css' %}">
</head>

<body>
    <nav class="navbar bg-dark border-bottom border-body" data-bs-theme="dark">
        <div class="container-fluid">
            <a class="navbar-brand web-name" href="{% url 'blog' %}">Django Blog</a>
            <div>
                {% block navbar %}

                {% endblock navbar %}
                {% if request.user.is_authenticated %}
                <a href="{% url 'logout' %}" class="btn btn-outline-light">🔒Logout</a>
                {% else %}
                <a href="{% url 'login' %}" class="btn btn-outline-light">🔓Login</a>
                {% endif %}
            </div>

        </div>
    </nav>

    {% block content %}

    {% endblock content %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm"
        crossorigin="anonymous"></script>
</body>

</html>

userapps/templates/home_user.html
{% extends 'main.html' %}

{% block title %}Home{% endblock title %}

{% block navbar %}
<a href="{% url 'createpost' %}" class="btn btn-outline-light">✏️</a>
{% endblock navbar %}

{% block content %}
<p class="text-center">
    Welcome {% if user.is_authenticated %}{{user.username}}{% endif %}
</p>
{% endblock content %}

userapps/templates/login_user.html
{% extends 'main.html' %}

{% block title %}Login Blog{% endblock title %}


{% block content %}

{% if page == 'register' %}

<form action="{% url 'register' %}" method="post" class="d-flex justify-content-center">

    {% csrf_token %}
    <div class="w-50 mt-5">
        <p class="fw-light fs-5 text-center">Create New Account</p>

        {% if messages %}
            {% for message in messages %}
                
            <div class="alert alert-{% if message.tags == 'error' %}danger{% else %}warning{% endif %} alert-dismissible fade show" role="alert">
                
                {{ message }} ({{ message.tags }})
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            {% endfor %}
        {% endif %}
        <div class="input-group mb-3">
            <span class="input-group-text" id="basic-addon1">{{form.username.label}}</span>
            {{form.username}}
        </div>
        <div class="input-group mb-3">
            <span class="input-group-text" id="basic-addon1">{{form.password1.label}}</span>
            {{form.password1}}
        </div>
        <div class="input-group mb-3">
            <span class="input-group-text" id="basic-addon1">{{form.password2.label}}</span>
            {{form.password2}}
        </div>
        <input type="submit" value="Register" class="btn btn-outline-secondary w-100">
    </div>

</form>

{% else %}

<form action="{% url 'login' %}" method="post" class="d-flex justify-content-center">

    {% csrf_token %}
    <div class="w-50 mt-5">
        <p class="fw-light fs-5 text-center">Login</p>

        {% if messages %}
            {% for message in messages %}
                
            <div class="alert alert-{% if message.tags == 'error' %}danger{% else %}warning{% endif %} alert-dismissible fade show" role="alert">
                
                {{ message }} ({{ message.tags }})
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            {% endfor %}
        {% endif %}
        

        <div class="input-group mb-3">
            <span class="input-group-text">@</span>
            <input type="text" name="username" class="form-control" placeholder="username">
        </div>
        <br />
        <div class="input-group mb-3">
            <span class="input-group-text">*</span>
            <input type="password" name="password" class="form-control" placeholder="password">
        </div>
        <br />
        <input type="submit" value="Login" class="btn btn-outline-secondary w-100">
        <p class="text-center mt-3">No Account? <a href="{% url 'register' %}">Register Now</a></p>
    </div>

</form>
{% endif %}
{% endblock content %}